# 1. Setting

## 1.1. Import

In [1]:
import numpy as np

## 1.2. Helper Functions

### 1.2.1. Print_vals

In [2]:
def print_vals(**kwargs):
    print(*[f'\n{key} {type(val)}\n{val}\n' for key, val in kwargs.items()], sep='-' * 16)

# 2. Array Creation

## 2.1. From shape or value

### 2.1.1. empty

In [3]:
a = np.empty(3)
b = np.empty((2, 3))
c = np.empty((2,), dtype=np.int8)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[6.98348878e-077 7.01413727e-009 2.16209973e+233]
----------------
b <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
----------------
c <class 'numpy.ndarray'>
[25 20]



### 2.1.2. empty_like

In [4]:
a = [[1, 2, 3], [4, 5, 6]]
b = np.empty_like(a)

print_vals(b=b)


b <class 'numpy.ndarray'>
[[ 539785256  807414835  538970665]
 [1044258848  779493438 1885431923]]



### 2.1.3. eye

In [5]:
a = np.eye(3)
b = np.eye(2, dtype=np.int8)
c = np.eye(4, k=1)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------------
b <class 'numpy.ndarray'>
[[1 0]
 [0 1]]
----------------
c <class 'numpy.ndarray'>
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]



### 2.1.4. identity

In [6]:
a = np.identity(3)
b = np.identity(2, dtype=np.int8)

print_vals(a=a, b=b)


a <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------------
b <class 'numpy.ndarray'>
[[1 0]
 [0 1]]



### 2.1.5. ones

In [7]:
a = np.ones(3)
b = np.ones((2, 3))
c = np.ones((2,), dtype=np.int8)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[1. 1. 1.]
----------------
b <class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]
----------------
c <class 'numpy.ndarray'>
[1 1]



### 2.1.6. ones_like

In [8]:
a = [[1, 2, 3], [4, 5, 6]]
b = np.ones_like(a)

print_vals(b=b)


b <class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]]



### 2.1.7. zeros

In [9]:
a = np.zeros(3)
b = np.zeros((2, 3))
c = np.zeros((2,), dtype=np.int8)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[0. 0. 0.]
----------------
b <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
----------------
c <class 'numpy.ndarray'>
[0 0]



### 2.1.8. zeros_like

In [10]:
a = [[1, 2, 3], [4, 5, 6]]
b = np.zeros_like(a)

print_vals(b=b)


b <class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]]



### 2.1.9. full

In [11]:
a = np.full(4, 3)
b = np.full((2, 3), 5)
c = np.full((4, 3), [3, 6, 9])

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[3 3 3 3]
----------------
b <class 'numpy.ndarray'>
[[5 5 5]
 [5 5 5]]
----------------
c <class 'numpy.ndarray'>
[[3 6 9]
 [3 6 9]
 [3 6 9]
 [3 6 9]]



### 2.1.10. full_like

In [12]:
a = [[1, 2, 3], [4, 5, 6]]
b = np.full_like(a, 7)

print_vals(b=b)


b <class 'numpy.ndarray'>
[[7 7 7]
 [7 7 7]]



## 2.2. From existing data

### 2.2.1. array

In [13]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 4.0])
c = np.array([[1, 2, 3], [4, 5, 6]])

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[1 2 3]
----------------
b <class 'numpy.ndarray'>
[1. 2. 4.]
----------------
c <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]



### 2.2.2. copy

In [14]:
a = np.array([1, 2, 3])
b = a
c = np.copy(a)

a[0] = 100

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[100   2   3]
----------------
b <class 'numpy.ndarray'>
[100   2   3]
----------------
c <class 'numpy.ndarray'>
[1 2 3]



## 2.3. Numerical ranges

### 2.3.1. arange

In [15]:
a = np.arange(3)
b = np.arange(4.0)
c = np.arange(3, 7)
d = np.arange(3, 10, 2)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[0 1 2]
----------------
b <class 'numpy.ndarray'>
[0. 1. 2. 3.]
----------------
c <class 'numpy.ndarray'>
[3 4 5 6]
----------------
d <class 'numpy.ndarray'>
[3 5 7 9]



### 2.3.2. linspace

In [16]:
a = np.linspace(2, 4, num=5)
b = np.linspace(2, 4, num=5, endpoint=False)
c = np.linspace(2, 4, num=5, retstep=True)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[2.  2.5 3.  3.5 4. ]
----------------
b <class 'numpy.ndarray'>
[2.  2.4 2.8 3.2 3.6]
----------------
c <class 'tuple'>
(array([2. , 2.5, 3. , 3.5, 4. ]), 0.5)



### 2.3.3. logspace

In [17]:
a = np.logspace(2, 3, num=4)
b = np.logspace(2, 3, num=4, endpoint=False)
c = np.logspace(2, 3, num=4, base=2)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[ 100.          215.443469    464.15888336 1000.        ]
----------------
b <class 'numpy.ndarray'>
[100.         177.827941   316.22776602 562.34132519]
----------------
c <class 'numpy.ndarray'>
[4.         5.0396842  6.34960421 8.        ]



### 2.3.4. geomspace

In [18]:
a = np.geomspace(1, 1000, num=4)
b = np.geomspace(1, 1000, num=3, endpoint=False)
c = np.geomspace(1, 256, num=9)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[   1.   10.  100. 1000.]
----------------
b <class 'numpy.ndarray'>
[  1.  10. 100.]
----------------
c <class 'numpy.ndarray'>
[  1.   2.   4.   8.  16.  32.  64. 128. 256.]



### 2.3.5. meshgrid

In [19]:
nx, ny = (3, 2)

x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)

xx, yy = np.meshgrid(x, y)
xs, ys = np.meshgrid(x, y, sparse=True)

print_vals(xx=xx, yy=yy, xs=xs, ys=ys)


xx <class 'numpy.ndarray'>
[[0.  0.5 1. ]
 [0.  0.5 1. ]]
----------------
yy <class 'numpy.ndarray'>
[[0. 0. 0.]
 [1. 1. 1.]]
----------------
xs <class 'numpy.ndarray'>
[[0.  0.5 1. ]]
----------------
ys <class 'numpy.ndarray'>
[[0.]
 [1.]]



## 2.4. Building matrices

### 2.4.1. diag

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b = np.diag(a)
c = np.diag(a, k=1)
d = np.diag(a, k=-1)
e = np.diag(np.diag(a))

print_vals(a=a, b=b, c=c, d=d, e=e)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------
b <class 'numpy.ndarray'>
[1 5 9]
----------------
c <class 'numpy.ndarray'>
[2 6]
----------------
d <class 'numpy.ndarray'>
[4 8]
----------------
e <class 'numpy.ndarray'>
[[1 0 0]
 [0 5 0]
 [0 0 9]]



### 2.4.2. diagflat

In [21]:
a = np.diagflat([[1, 2], [3, 4]])
b = np.diagflat([1, 2, 3], 1)

print_vals(a=a, b=b)


a <class 'numpy.ndarray'>
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
----------------
b <class 'numpy.ndarray'>
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]



### 2.4.3. tri

In [22]:
a = np.tri(3)
b = np.tri(4, 3)
c = np.tri(3, 5, -1)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
----------------
b <class 'numpy.ndarray'>
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------------
c <class 'numpy.ndarray'>
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]



### 2.4.4. tril

In [23]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

b = np.tril(a)
c = np.tril(a, -1)

print_vals(b=b, c=c)


b <class 'numpy.ndarray'>
[[ 1  0  0]
 [ 4  5  0]
 [ 7  8  9]
 [10 11 12]]
----------------
c <class 'numpy.ndarray'>
[[ 0  0  0]
 [ 4  0  0]
 [ 7  8  0]
 [10 11 12]]



### 2.4.5. triu

In [24]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

b = np.triu(a)
c = np.triu(a, -1)

print_vals(b=b, c=c)


b <class 'numpy.ndarray'>
[[1 2 3]
 [0 5 6]
 [0 0 9]
 [0 0 0]]
----------------
c <class 'numpy.ndarray'>
[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [ 0  0 12]]



### 2.4.6. vander

In [25]:
a = np.arange(5)

b = np.vander(a, 3)
c = np.vander(a, 3, increasing=True)

print_vals(b=b, c=c)


b <class 'numpy.ndarray'>
[[ 0  0  1]
 [ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
----------------
c <class 'numpy.ndarray'>
[[ 1  0  0]
 [ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]



# 3. Array Indexing

## 3.1. Generating index arrays

### 3.1.1. c_

Translates slice objects to concatenation along the second axis.

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

c = np.c_[a, b]

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
----------------
b <class 'numpy.ndarray'>
[[ 7  8  9]
 [10 11 12]]
----------------
c <class 'numpy.ndarray'>
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]



### 3.1.2. r_

Translates slice objects to concatenation along the first axis.

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

c = np.r_[a, b]

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
----------------
b <class 'numpy.ndarray'>
[[ 7  8  9]
 [10 11 12]]
----------------
c <class 'numpy.ndarray'>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



### 3.1.3. s_

A nicer way to build up index tuples for arrays.

In [28]:
a = np.array([0, 1, 2, 3, 4, 5, 6])
b = np.s_[2::2]

print_vals(**{'a[b]': a[b]})


a[b] <class 'numpy.ndarray'>
[2 4 6]



### 3.1.4. where

Return elements chosen from x or y depending on condition.

In [29]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.where(a < 5, a, a * 10)

c = np.array([[True, False], [False, True]])
d = np.array([[1, 2], [3, 4]])
e = np.array([[5, 6], [7, 8]])
f = np.where(c, d, e)

print_vals(b=b, f=f)


b <class 'numpy.ndarray'>
[ 1  2  3  4 50 60 70 80 90]
----------------
f <class 'numpy.ndarray'>
[[1 6]
 [7 4]]



### 3.1.5. indices

Return an array representing the indices of a grid.

In [30]:
a = np.indices((2, 3))
b = np.indices((2, 3), sparse=True)

print_vals(a=a, b=b)


a <class 'numpy.ndarray'>
[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]
----------------
b <class 'tuple'>
(array([[0],
       [1]]), array([[0, 1, 2]]))



## 3.2. Indexing-like operations

### 3.2.1. select

Return an array drawn from elements in choicelist, depending on conditions.

In [31]:
a = np.array([1, 2, 3, 4, 5, 6])

condlist = [a < 3, a > 3]
choicelist = [a, a ** 2]

b = np.select(condlist, choicelist)
c = np.select(condlist, choicelist, -1)

print_vals(b=b, c=c)


b <class 'numpy.ndarray'>
[ 1  2  0 16 25 36]
----------------
c <class 'numpy.ndarray'>
[ 1  2 -1 16 25 36]



## 3.3. Inserting data into arrays

### 3.3.1. put

Replaces specified elements of an array with given values.

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])

idx = [0, 2]
val = [100, 200]

np.put(a, idx, val)

print_vals(a=a)


a <class 'numpy.ndarray'>
[100   2 200   4   5   6]



## 3.4. Iterating over arrays

### 3.4.1. ndenumerate

Multidimensional index iterator.

In [33]:
a = np.array([[1, 2], [3, 4]])

for idx, val in np.ndenumerate(a):
    print(idx, val)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


### 3.4.2. ndindex

An N-dimensional iterator object to index arrays.

In [34]:
for idx in np.ndindex(3, 2, 1):
    print(idx)

print('-' * 16)

a = (3, 2, 1)
for idx in np.ndindex(a):
    print(idx)

(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)
(2, 0, 0)
(2, 1, 0)
----------------
(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)
(2, 0, 0)
(2, 1, 0)


# 4. Attributes

## 4.1. Memory layout

### 4.1.1. shape

Tuple of array dimensions.

In [35]:
a = np.array([1, 2, 3, 4])
b = np.zeros((2, 3, 4))

c = a.shape
d = b.shape

e = np.copy(a)
e.shape = (2, 2)

f = np.copy(a)
f.shape = (-1, 2)

print_vals(c=c, d=d, e=e, f=f)


c <class 'tuple'>
(4,)
----------------
d <class 'tuple'>
(2, 3, 4)
----------------
e <class 'numpy.ndarray'>
[[1 2]
 [3 4]]
----------------
f <class 'numpy.ndarray'>
[[1 2]
 [3 4]]



### 4.1.2. ndim

Number of array dimensions.

In [36]:
a = np.array([1, 2, 3, 4])
b = np.zeros((2, 3, 4))

c = a.ndim
d = b.ndim

print_vals(c=c, d=d)


c <class 'int'>
1
----------------
d <class 'int'>
3



### 4.1.3. size

Number of elements in the array.

In [37]:
a = np.array([1, 2, 3, 4])
b = np.zeros((2, 3, 4))

c = a.size
d = b.size

print_vals(c=c, d=d)


c <class 'int'>
4
----------------
d <class 'int'>
24



## 4.2. Data type

### 4.2.1. dtype

Data-type of the array's elements.

In [38]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4.0])

c = a.dtype
d = b.dtype

print_vals(c=c, d=d)


c <class 'numpy.dtype[int32]'>
int32
----------------
d <class 'numpy.dtype[float64]'>
float64



## 4.3. Other attributes

### 4.3.1. T

The transposed array.

In [39]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.T

print_vals(a=a, b=b)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
----------------
b <class 'numpy.ndarray'>
[[1 4]
 [2 5]
 [3 6]]



### 4.3.2. flat

A 1-D iterator over the array.

In [40]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.flat[3]

c = np.copy(a)
c.flat = 100

d = np.copy(a)
d.flat[[1, 4]] = 100

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
----------------
b <class 'numpy.int32'>
4
----------------
c <class 'numpy.ndarray'>
[[100 100 100]
 [100 100 100]]
----------------
d <class 'numpy.ndarray'>
[[  1 100   3]
 [  4 100   6]]



# 5. Methods

For the following methods there are also corresponding functions in numpy.

```
all, any, argmax, argmin, argpartition, argsort, choose, clip, compress, copy, cumprod, cumsum, diagonal, imag, max, mean, min, nonzero, partition, prod, ptp, put, ravel, real, repeat, reshape, round, searchsorted, sort, squeeze, std, sum, swapaxes, take, trace, transpose, var
```

## 5.1. Array conversion

### 5.1.1. item

Copy an element of an array to a standard Python scalar and return it.

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.item(4)
c = a.item((1, 2))

print_vals(b=b, c=c)


b <class 'int'>
5
----------------
c <class 'int'>
6



### 5.1.2. tolist

Return the array as an a.ndim-levels deep nested list of Python scalars.

In [42]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.tolist()
c = list(a)

print_vals(b=b, c=c)


b <class 'list'>
[[1, 2, 3], [4, 5, 6]]
----------------
c <class 'list'>
[array([1, 2, 3]), array([4, 5, 6])]



### 5.1.3. astype

Copy of the array, cast to a specified type.

In [43]:
a = np.array([1, 2, 3, 4])
b = a.dtype

c = a.astype(np.float64)
d = c.dtype

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[1 2 3 4]
----------------
b <class 'numpy.dtype[int32]'>
int32
----------------
c <class 'numpy.ndarray'>
[1. 2. 3. 4.]
----------------
d <class 'numpy.dtype[float64]'>
float64



### 5.1.4. copy

Return a copy of the array.

In [44]:
a = np.array([1, 2, 3])
b = a
c = a.copy()

a[0] = 100

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[100   2   3]
----------------
b <class 'numpy.ndarray'>
[100   2   3]
----------------
c <class 'numpy.ndarray'>
[1 2 3]



### 5.1.5. fill

Fill the array with a scalar value.

In [45]:
a = np.empty(3)
a.fill(100)

print_vals(a=a)


a <class 'numpy.ndarray'>
[100. 100. 100.]



## 5.2. Shape manipulation

### 5.2.1. reshape

Returns an array containing the same data with a new shape.

In [46]:
a = np.arange(12)

b = a.reshape(3, 4)
c = a.reshape(3, -1)
d = a.reshape((3, -1))

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11]
----------------
b <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------
c <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------
d <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



### 5.2.2. resize

Change shape and size of array in-place.

In [47]:
a = np.arange(12)

b = a.copy()
b.resize(3, 4)

c = a.copy()
c.resize((3, 4))

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11]
----------------
b <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------
c <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



### 5.2.3. transpose

Returns a view of the array with axes transposed.

In [48]:
a = np.arange(6).reshape(2, 1, 3)

b = a.transpose()           # shape: (3, 1, 2)
c = a.transpose(2, 0, 1)    # shape: (3, 2, 1)
d = a.transpose((1, 0, 2))  # shape: (1, 2, 3)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[[0 1 2]]

 [[3 4 5]]]
----------------
b <class 'numpy.ndarray'>
[[[0 3]]

 [[1 4]]

 [[2 5]]]
----------------
c <class 'numpy.ndarray'>
[[[0]
  [3]]

 [[1]
  [4]]

 [[2]
  [5]]]
----------------
d <class 'numpy.ndarray'>
[[[0 1 2]
  [3 4 5]]]



### 5.2.4. swapaxes

Return a view of the array with axis1 and axis2 interchanged.

In [49]:
a = np.arange(6).reshape((2, 1, 3))
b = a.swapaxes(1, 2)

print_vals(a=a, b=b)


a <class 'numpy.ndarray'>
[[[0 1 2]]

 [[3 4 5]]]
----------------
b <class 'numpy.ndarray'>
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]



### 5.2.5. flatten

Return a copy of the array collapsed into one dimension.

In [50]:
a = np.arange(6).reshape(2, 3)
b = a.flatten()

print_vals(a=a, b=b)


a <class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]
----------------
b <class 'numpy.ndarray'>
[0 1 2 3 4 5]



## 5.3. Item selection and manipulation

### 5.3.1. put

Set `a.flat[n] = values[n]` for all *n* in indices.

In [51]:
a = np.array([1, 2, 3, 4, 5, 6])

idx = [0, 2]
val = [100, 200]

a.put(idx, val)

print_vals(a=a)


a <class 'numpy.ndarray'>
[100   2 200   4   5   6]



### 5.3.2. repeat

Repeat elements of an array.

In [52]:
a = np.arange(6).reshape(2, 3)
b = a.repeat(3)

print_vals(a=a, b=b)


a <class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]
----------------
b <class 'numpy.ndarray'>
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]



### 5.3.3. sort

Sort an array in-place.

In [53]:
a = np.array([[2, 5, 4], [6, 3, 1]])

b = a.copy()
b.sort()

c = a.copy()
c.sort(0)

d = a.copy()
d.sort(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[2 5 4]
 [6 3 1]]
----------------
b <class 'numpy.ndarray'>
[[2 4 5]
 [1 3 6]]
----------------
c <class 'numpy.ndarray'>
[[2 3 1]
 [6 5 4]]
----------------
d <class 'numpy.ndarray'>
[[2 4 5]
 [1 3 6]]



## 5.4. Calculation

### 5.4.1. max

Return the maximum along a given axis.

In [54]:
a = np.array([[6, 2, 19], [-1, 4, 0]])

b = a.max()
c = a.max(0)
d = a.max(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[ 6  2 19]
 [-1  4  0]]
----------------
b <class 'numpy.int32'>
19
----------------
c <class 'numpy.ndarray'>
[ 6  4 19]
----------------
d <class 'numpy.ndarray'>
[19  4]



### 5.4.2. argmax

Return indices of the maximum values along the given axis.

In [55]:
a = np.array([[6, 2, 19], [-1, 4, 0]])

b = a.argmax()
c = a.argmax(0)
d = a.argmax(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[ 6  2 19]
 [-1  4  0]]
----------------
b <class 'numpy.int64'>
2
----------------
c <class 'numpy.ndarray'>
[0 1 0]
----------------
d <class 'numpy.ndarray'>
[2 1]



### 5.4.3. min

Return the minimum along a given axis.

In [56]:
a = np.array([[6, 2, 19], [-1, 4, 0]])

b = a.min()
c = a.min(0)
d = a.min(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[ 6  2 19]
 [-1  4  0]]
----------------
b <class 'numpy.int32'>
-1
----------------
c <class 'numpy.ndarray'>
[-1  2  0]
----------------
d <class 'numpy.ndarray'>
[ 2 -1]



### 5.4.4. argmin

Return indices of the minimum values along the given axis.

In [57]:
a = np.array([[6, 2, 19], [-1, 4, 0]])

b = a.argmin()
c = a.argmin(0)
d = a.argmin(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[ 6  2 19]
 [-1  4  0]]
----------------
b <class 'numpy.int64'>
3
----------------
c <class 'numpy.ndarray'>
[1 0 1]
----------------
d <class 'numpy.ndarray'>
[1 0]



### 5.4.5. clip

Return an array whose values are limited to `[min, max]`.

In [58]:
a = np.arange(10)

b = a.clip(3, 7)

c = a.copy()
c.clip(3, 7, out=c)

d = a.clip([2, 0, 1, 3, 1, 4, 2, 4, 0, 3], 5)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
----------------
b <class 'numpy.ndarray'>
[3 3 3 3 4 5 6 7 7 7]
----------------
c <class 'numpy.ndarray'>
[3 3 3 3 4 5 6 7 7 7]
----------------
d <class 'numpy.ndarray'>
[2 1 2 3 4 5 5 5 5 5]



### 5.4.6. round

Return *a* with each element rounded to the given number of decimals.

In [59]:
a = np.array([3.14159265, 2.17828])

b = a.round()
c = a.round(3)

print_vals(b=b, c=c)


b <class 'numpy.ndarray'>
[3. 2.]
----------------
c <class 'numpy.ndarray'>
[3.142 2.178]



### 5.4.7. trace

Return the sum along diagonals of the array.

In [60]:
a = np.arange(9).reshape((3, 3))

b = a.trace()
c = a.trace(1)
d = a.trace(-1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]
----------------
b <class 'numpy.int32'>
12
----------------
c <class 'numpy.int32'>
6
----------------
d <class 'numpy.int32'>
10



### 5.4.8. sum

Return the sum of the array elements over the given axis.

In [61]:
a = np.arange(8).reshape((2, 4))

b = a.sum()
c = a.sum(0)
d = a.sum(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[0 1 2 3]
 [4 5 6 7]]
----------------
b <class 'numpy.int32'>
28
----------------
c <class 'numpy.ndarray'>
[ 4  6  8 10]
----------------
d <class 'numpy.ndarray'>
[ 6 22]



### 5.4.9. cumsum

Return the cumulative sum of the elements along the given axis.

In [62]:
a = np.arange(1, 10).reshape((3, 3))

b = a.cumsum()
c = a.cumsum(0)
d = a.cumsum(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------
b <class 'numpy.ndarray'>
[ 1  3  6 10 15 21 28 36 45]
----------------
c <class 'numpy.ndarray'>
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
----------------
d <class 'numpy.ndarray'>
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]



### 5.4.10. mean

Returns the average of the array elements along given axis.

In [63]:
a = np.arange(1, 10).reshape((3, 3))

b = a.mean()
c = a.mean(0)
d = a.mean(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------
b <class 'numpy.float64'>
5.0
----------------
c <class 'numpy.ndarray'>
[4. 5. 6.]
----------------
d <class 'numpy.ndarray'>
[2. 5. 8.]



### 5.4.11. var

Returns the variance of the array elements, along given axis.

In [64]:
a = np.arange(8).reshape((2, 4))

b = a.var()
c = a.var(0)
d = a.var(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[0 1 2 3]
 [4 5 6 7]]
----------------
b <class 'numpy.float64'>
5.25
----------------
c <class 'numpy.ndarray'>
[4. 4. 4. 4.]
----------------
d <class 'numpy.ndarray'>
[1.25 1.25]



### 5.4.12. std

Returns the standard deviation of the array elements along given axis.

In [65]:
a = np.arange(8).reshape((2, 4))

b = a.std()
c = a.std(0)
d = a.std(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[0 1 2 3]
 [4 5 6 7]]
----------------
b <class 'numpy.float64'>
2.29128784747792
----------------
c <class 'numpy.ndarray'>
[2. 2. 2. 2.]
----------------
d <class 'numpy.ndarray'>
[1.11803399 1.11803399]



### 5.4.13. prod

Return the product of the array elements over the given axis.

In [66]:
a = np.arange(1, 9).reshape((2, 4))

b = a.prod()
c = a.prod(0)
d = a.prod(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
----------------
b <class 'numpy.int32'>
40320
----------------
c <class 'numpy.ndarray'>
[ 5 12 21 32]
----------------
d <class 'numpy.ndarray'>
[  24 1680]



### 5.4.14. cumprod

Return the cumulative product of the elements along the given axis.

In [67]:
a = np.arange(1, 10).reshape((3, 3))

b = a.cumprod()
c = a.cumprod(0)
d = a.cumprod(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------
b <class 'numpy.ndarray'>
[     1      2      6     24    120    720   5040  40320 362880]
----------------
c <class 'numpy.ndarray'>
[[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]
----------------
d <class 'numpy.ndarray'>
[[  1   2   6]
 [  4  20 120]
 [  7  56 504]]



### 5.4.15. all

Returns True if all elements evaluate to True.

In [68]:
a = np.array([[True, True, False], [False, True, False], [True, True, True]])

b = a.all()
c = a.all(0)
d = a.all(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[ True  True False]
 [False  True False]
 [ True  True  True]]
----------------
b <class 'numpy.bool_'>
False
----------------
c <class 'numpy.ndarray'>
[False  True False]
----------------
d <class 'numpy.ndarray'>
[False False  True]



### 5.4.16. any

Returns True if any of the elements of *a* evaluate to True.

In [69]:
a = np.array([[True, True, False], [False, True, False], [True, True, False]])

b = a.any()
c = a.any(0)
d = a.any(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[ True  True False]
 [False  True False]
 [ True  True False]]
----------------
b <class 'numpy.bool_'>
True
----------------
c <class 'numpy.ndarray'>
[ True  True False]
----------------
d <class 'numpy.ndarray'>
[ True  True  True]

