1. numpy 패키지를 np라는 이름으로 임포트(import)

### 0. numpy 패키지를 np라는 이름으로 임포트(import)

### 1. 영벡터

자연수 n이 입력으로 주어질 때 길이 n의 영벡터를 반환하는 함수를 작성하여라.

Example
```
sol_1 = solution01(4)  # [0. 0. 0. 0.]
sol_2 = solution01(5)  # [0. 0. 0. 0. 0.]
```

In [1]:
def solution01(n):
    pass

In [2]:
sol_1 = solution01(4)  # [0. 0. 0. 0.]
sol_2 = solution01(5)  # [0. 0. 0. 0. 0.]

print(sol_1)
print(sol_2)

None
None


### 2. 0 & 1

자연수 n이 입력으로 주어질 때 홀수 인덱스는 0, 짝수 인덱스는 1을 가지는 길이 n 벡터를 반환하는 함수를 작성하여라.

Example
```
sol_1 = solution02(5)   # [1. 0. 1. 0. 1.]
sol_2 = solution02(10)  # [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
```

In [3]:
def solution02(n):
    pass

In [4]:
sol_1 = solution02(5)   # [1. 0. 1. 0. 1.]
sol_2 = solution02(10)  # [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]

print(sol_1)
print(sol_2)

None
None


### 3. 배수

자연수 n(≤100)이 입력으로 주어질 때 100 이하의 자연수 중 n의 배수로만 이루어진 벡터를 반환하는 함수를 작성하여라.

Example
```
sol_1 = solution03(7)   # [ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]
sol_2 = solution03(13)  # [13 26 39 52 65 78 91]
```

In [5]:
def solution03(n):
    pass

In [6]:
sol_1 = solution03(7)   # [ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]
sol_2 = solution03(13)  # [13 26 39 52 65 78 91]

print(sol_1)
print(sol_2)

None
None


### 4. 정방행렬

자연수 n이 입력으로 주어질 때 1부터 n<sup>2</sup>까지의 자연수를 원소로 가지는 정방행렬을 반환하는 함수를 작성하여라.

Example
```
sol_1 = solution04(3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

sol_2 = solution04(4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
```

In [7]:
def solution04(n):
    pass

In [8]:
sol_1 = solution04(3)
sol_2 = solution04(4)

print(sol_1)
print(sol_2)

None
None


### 5. 등차수열

자연수 n이 입력으로 주어질 때 0부터 1까지 등차수열을 이루는 길이 n 벡터를 반환하는 함수를 작성하여라.

Example
```
sol_1 = solution05(6)   # [0.  0.2 0.4 0.6 0.8 1. ]
sol_2 = solution05(11)  # [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
```

In [9]:
def solution05(n):
    pass

In [10]:
sol_1 = solution05(6)   # [0.  0.2 0.4 0.6 0.8 1. ]
sol_2 = solution05(11)  # [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

print(sol_1)
print(sol_2)

None
None
