# 1. Setting

## 1.1. Import

In [1]:
import numpy as np

## 1.2. Helper Functions

### 1.2.1. Print_vals

In [2]:
def print_vals(**kwargs):
    print(*[f'\n{key} {type(val)}\n{val}\n' for key, val in kwargs.items()], sep='-' * 16)

# 2. Array Creation

## 2.1. From shape or value

### 2.1.5. ones

In [7]:
a = np.ones(3)
b = np.ones((2, 3))
c = np.ones((2,), dtype=np.int8)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[1. 1. 1.]
----------------
b <class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]
----------------
c <class 'numpy.ndarray'>
[1 1]



### 2.1.6. ones_like

In [8]:
a = [[1, 2, 3], [4, 5, 6]]
b = np.ones_like(a)

print_vals(b=b)


b <class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]]



### 2.1.7. zeros

In [9]:
a = np.zeros(3)
b = np.zeros((2, 3))
c = np.zeros((2,), dtype=np.int8)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[0. 0. 0.]
----------------
b <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
----------------
c <class 'numpy.ndarray'>
[0 0]



### 2.1.8. zeros_like

In [10]:
a = [[1, 2, 3], [4, 5, 6]]
b = np.zeros_like(a)

print_vals(b=b)


b <class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]]



### 2.1.9. full

In [11]:
a = np.full(4, 3)
b = np.full((2, 3), 5)
c = np.full((4, 3), [3, 6, 9])

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[3 3 3 3]
----------------
b <class 'numpy.ndarray'>
[[5 5 5]
 [5 5 5]]
----------------
c <class 'numpy.ndarray'>
[[3 6 9]
 [3 6 9]
 [3 6 9]
 [3 6 9]]



### 2.1.10. full_like

In [12]:
a = [[1, 2, 3], [4, 5, 6]]
b = np.full_like(a, 7)

print_vals(b=b)


b <class 'numpy.ndarray'>
[[7 7 7]
 [7 7 7]]



## 2.2. From existing data

### 2.2.1. array

In [13]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 4.0])
c = np.array([[1, 2, 3], [4, 5, 6]])

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[1 2 3]
----------------
b <class 'numpy.ndarray'>
[1. 2. 4.]
----------------
c <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]



### 2.2.2. copy

In [14]:
a = np.array([1, 2, 3])
b = a
c = np.copy(a)

a[0] = 100

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[100   2   3]
----------------
b <class 'numpy.ndarray'>
[100   2   3]
----------------
c <class 'numpy.ndarray'>
[1 2 3]



## 2.3. Numerical ranges

### 2.3.1. arange

In [15]:
a = np.arange(3)
b = np.arange(4.0)
c = np.arange(3, 7)
d = np.arange(3, 10, 2)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[0 1 2]
----------------
b <class 'numpy.ndarray'>
[0. 1. 2. 3.]
----------------
c <class 'numpy.ndarray'>
[3 4 5 6]
----------------
d <class 'numpy.ndarray'>
[3 5 7 9]



### 2.3.2. linspace

In [16]:
a = np.linspace(2, 4, num=5)
b = np.linspace(2, 4, num=5, endpoint=False)
c = np.linspace(2, 4, num=5, retstep=True)

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[2.  2.5 3.  3.5 4. ]
----------------
b <class 'numpy.ndarray'>
[2.  2.4 2.8 3.2 3.6]
----------------
c <class 'tuple'>
(array([2. , 2.5, 3. , 3.5, 4. ]), 0.5)



# 3. Array Indexing

## 3.1. Generating index arrays

### 3.1.1. c_

Translates slice objects to concatenation along the second axis.

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

c = np.c_[a, b]

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
----------------
b <class 'numpy.ndarray'>
[[ 7  8  9]
 [10 11 12]]
----------------
c <class 'numpy.ndarray'>
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]



### 3.1.2. r_

Translates slice objects to concatenation along the first axis.

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

c = np.r_[a, b]

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
----------------
b <class 'numpy.ndarray'>
[[ 7  8  9]
 [10 11 12]]
----------------
c <class 'numpy.ndarray'>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



### 3.1.4. where

Return elements chosen from x or y depending on condition.

In [29]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.where(a < 5, a, a * 10)

c = np.array([[True, False], [False, True]])
d = np.array([[1, 2], [3, 4]])
e = np.array([[5, 6], [7, 8]])
f = np.where(c, d, e)

print_vals(b=b, f=f)


b <class 'numpy.ndarray'>
[ 1  2  3  4 50 60 70 80 90]
----------------
f <class 'numpy.ndarray'>
[[1 6]
 [7 4]]



# 4. Attributes

## 4.1. Memory layout

### 4.1.1. shape

Tuple of array dimensions.

In [35]:
a = np.array([1, 2, 3, 4])
b = np.zeros((2, 3, 4))

c = a.shape
d = b.shape

e = np.copy(a)
e.shape = (2, 2)

f = np.copy(a)
f.shape = (-1, 2)

print_vals(c=c, d=d, e=e, f=f)


c <class 'tuple'>
(4,)
----------------
d <class 'tuple'>
(2, 3, 4)
----------------
e <class 'numpy.ndarray'>
[[1 2]
 [3 4]]
----------------
f <class 'numpy.ndarray'>
[[1 2]
 [3 4]]



### 4.1.2. ndim

Number of array dimensions.

In [36]:
a = np.array([1, 2, 3, 4])
b = np.zeros((2, 3, 4))

c = a.ndim
d = b.ndim

print_vals(c=c, d=d)


c <class 'int'>
1
----------------
d <class 'int'>
3



### 4.1.3. size

Number of elements in the array.

In [37]:
a = np.array([1, 2, 3, 4])
b = np.zeros((2, 3, 4))

c = a.size
d = b.size

print_vals(c=c, d=d)


c <class 'int'>
4
----------------
d <class 'int'>
24



## 4.2. Data type

### 4.2.1. dtype

Data-type of the array's elements.

In [38]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4.0])

c = a.dtype
d = b.dtype

print_vals(c=c, d=d)


c <class 'numpy.dtype[int32]'>
int32
----------------
d <class 'numpy.dtype[float64]'>
float64



## 4.3. Other attributes

### 4.3.1. T

The transposed array.

In [39]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.T

print_vals(a=a, b=b)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
----------------
b <class 'numpy.ndarray'>
[[1 4]
 [2 5]
 [3 6]]



# 5. Methods

For the following methods there are also corresponding functions in numpy.

```
all, any, argmax, argmin, argpartition, argsort, choose, clip, compress, copy, cumprod, cumsum, diagonal, imag, max, mean, min, nonzero, partition, prod, ptp, put, ravel, real, repeat, reshape, round, searchsorted, sort, squeeze, std, sum, swapaxes, take, trace, transpose, var
```

## 5.1. Array conversion

### 5.1.2. tolist

Return the array as an a.ndim-levels deep nested list of Python scalars.

In [42]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.tolist()
c = list(a)

print_vals(b=b, c=c)


b <class 'list'>
[[1, 2, 3], [4, 5, 6]]
----------------
c <class 'list'>
[array([1, 2, 3]), array([4, 5, 6])]



### 5.1.4. copy

Return a copy of the array.

In [44]:
a = np.array([1, 2, 3])
b = a
c = a.copy()

a[0] = 100

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[100   2   3]
----------------
b <class 'numpy.ndarray'>
[100   2   3]
----------------
c <class 'numpy.ndarray'>
[1 2 3]



### 5.1.5. fill

Fill the array with a scalar value.

In [45]:
a = np.empty(3)
a.fill(100)

print_vals(a=a)


a <class 'numpy.ndarray'>
[100. 100. 100.]



## 5.2. Shape manipulation

### 5.2.1. reshape

Returns an array containing the same data with a new shape.

In [46]:
a = np.arange(12)

b = a.reshape(3, 4)
c = a.reshape(3, -1)
d = a.reshape((3, -1))

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11]
----------------
b <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------
c <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------
d <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



### 5.2.2. resize

Change shape and size of array in-place.

In [47]:
a = np.arange(12)

b = a.copy()
b.resize(3, 4)

c = a.copy()
c.resize((3, 4))

print_vals(a=a, b=b, c=c)


a <class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11]
----------------
b <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------
c <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



### 5.2.5. flatten

Return a copy of the array collapsed into one dimension.

In [50]:
a = np.arange(6).reshape(2, 3)
b = a.flatten()

print_vals(a=a, b=b)


a <class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]
----------------
b <class 'numpy.ndarray'>
[0 1 2 3 4 5]



## 5.3. Item selection and manipulation

### 5.3.2. repeat

Repeat elements of an array.

In [52]:
a = np.arange(6).reshape(2, 3)
b = a.repeat(3)

print_vals(a=a, b=b)


a <class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]
----------------
b <class 'numpy.ndarray'>
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]



### 5.3.3. sort

Sort an array in-place.

In [53]:
a = np.array([[2, 5, 4], [6, 3, 1]])

b = a.copy()
b.sort()

c = a.copy()
c.sort(0)

d = a.copy()
d.sort(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[2 5 4]
 [6 3 1]]
----------------
b <class 'numpy.ndarray'>
[[2 4 5]
 [1 3 6]]
----------------
c <class 'numpy.ndarray'>
[[2 3 1]
 [6 5 4]]
----------------
d <class 'numpy.ndarray'>
[[2 4 5]
 [1 3 6]]



## 5.4. Calculation

### 5.4.1. max

Return the maximum along a given axis.

In [54]:
a = np.array([[6, 2, 19], [-1, 4, 0]])

b = a.max()
c = a.max(0)
d = a.max(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[ 6  2 19]
 [-1  4  0]]
----------------
b <class 'numpy.int32'>
19
----------------
c <class 'numpy.ndarray'>
[ 6  4 19]
----------------
d <class 'numpy.ndarray'>
[19  4]



### 5.4.2. argmax

Return indices of the maximum values along the given axis.

In [55]:
a = np.array([[6, 2, 19], [-1, 4, 0]])

b = a.argmax()
c = a.argmax(0)
d = a.argmax(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[ 6  2 19]
 [-1  4  0]]
----------------
b <class 'numpy.int64'>
2
----------------
c <class 'numpy.ndarray'>
[0 1 0]
----------------
d <class 'numpy.ndarray'>
[2 1]



### 5.4.3. min

Return the minimum along a given axis.

In [56]:
a = np.array([[6, 2, 19], [-1, 4, 0]])

b = a.min()
c = a.min(0)
d = a.min(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[ 6  2 19]
 [-1  4  0]]
----------------
b <class 'numpy.int32'>
-1
----------------
c <class 'numpy.ndarray'>
[-1  2  0]
----------------
d <class 'numpy.ndarray'>
[ 2 -1]



### 5.4.4. argmin

Return indices of the minimum values along the given axis.

In [57]:
a = np.array([[6, 2, 19], [-1, 4, 0]])

b = a.argmin()
c = a.argmin(0)
d = a.argmin(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[ 6  2 19]
 [-1  4  0]]
----------------
b <class 'numpy.int64'>
3
----------------
c <class 'numpy.ndarray'>
[1 0 1]
----------------
d <class 'numpy.ndarray'>
[1 0]



### 5.4.5. clip

Return an array whose values are limited to `[min, max]`.

In [58]:
a = np.arange(10)

b = a.clip(3, 7)

c = a.copy()
c.clip(3, 7, out=c)

d = a.clip([2, 0, 1, 3, 1, 4, 2, 4, 0, 3], 5)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
----------------
b <class 'numpy.ndarray'>
[3 3 3 3 4 5 6 7 7 7]
----------------
c <class 'numpy.ndarray'>
[3 3 3 3 4 5 6 7 7 7]
----------------
d <class 'numpy.ndarray'>
[2 1 2 3 4 5 5 5 5 5]



### 5.4.6. round

Return *a* with each element rounded to the given number of decimals.

In [59]:
a = np.array([3.14159265, 2.17828])

b = a.round()
c = a.round(3)

print_vals(b=b, c=c)


b <class 'numpy.ndarray'>
[3. 2.]
----------------
c <class 'numpy.ndarray'>
[3.142 2.178]



### 5.4.8. sum

Return the sum of the array elements over the given axis.

In [61]:
a = np.arange(8).reshape((2, 4))

b = a.sum()
c = a.sum(0)
d = a.sum(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[0 1 2 3]
 [4 5 6 7]]
----------------
b <class 'numpy.int32'>
28
----------------
c <class 'numpy.ndarray'>
[ 4  6  8 10]
----------------
d <class 'numpy.ndarray'>
[ 6 22]



### 5.4.10. mean

Returns the average of the array elements along given axis.

In [63]:
a = np.arange(1, 10).reshape((3, 3))

b = a.mean()
c = a.mean(0)
d = a.mean(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------
b <class 'numpy.float64'>
5.0
----------------
c <class 'numpy.ndarray'>
[4. 5. 6.]
----------------
d <class 'numpy.ndarray'>
[2. 5. 8.]



### 5.4.12. std

Returns the standard deviation of the array elements along given axis.

In [65]:
a = np.arange(8).reshape((2, 4))

b = a.std()
c = a.std(0)
d = a.std(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[0 1 2 3]
 [4 5 6 7]]
----------------
b <class 'numpy.float64'>
2.29128784747792
----------------
c <class 'numpy.ndarray'>
[2. 2. 2. 2.]
----------------
d <class 'numpy.ndarray'>
[1.11803399 1.11803399]



### 5.4.13. prod

Return the product of the array elements over the given axis.

In [66]:
a = np.arange(1, 9).reshape((2, 4))

b = a.prod()
c = a.prod(0)
d = a.prod(1)

print_vals(a=a, b=b, c=c, d=d)


a <class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
----------------
b <class 'numpy.int32'>
40320
----------------
c <class 'numpy.ndarray'>
[ 5 12 21 32]
----------------
d <class 'numpy.ndarray'>
[  24 1680]

